file=open("notes.txt","a")
file.write("\n welcome to python")
file.close()
file=open("notes.txt","r")
content=file.read()
lines=len(content.splitlines())
words=len(content.split())
characters=len(content)
print("Lines:",lines,"words:",words,"characters:",characters)
file.close()